# ████████╗██╗  ██╗███████╗███╗   ███╗███████╗
# ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝
#    ██║   ███████║█████╗  ██╔████╔██║█████╗  
#    ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝  
#    ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
# 

[flavor]
# dark = "catppuccin-mocha"
# dark = "gruvbox-dark"
# dark = "kanagawa"

