#!/usr/bin/env zsh
# ┌─┐┌─┐┬ ┬  ┬┌┐┌┬┌┬┐
# ┌─┘└─┐├─┤  │││││ │
# └─┘└─┘┴ ┴  ┴┘└┘┴ ┴
#--------------------------------------------
# (c) maarutan   https://github.com/maarutan

# Core
source "$HOME/zsh/karnel/core/beauty"
source "$HOME/zsh/karnel/core/environments"
source "$HOME/zsh/karnel/core/aliases"
source "$HOME/zsh/karnel/core/themeinit"
source "$HOME/zsh/karnel/core/__zinit__/zinit"
source "$HOME/zsh/karnel/core/keybindings"
source "$HOME/zsh/karnel/core/funcinit"
source "$HOME/zsh/karnel/core/abbreviation"
